package differential

// P1 coverage scripts (§7): hashes, lists, sets, sorted sets. Each script
// starts from an empty keyspace (the runner FLUSHALLs first). Random
// commands are exercised only through deterministic forms (single-element
// collections, count >= cardinality) or unordered matchers.

import "strconv"

var p1HashScripts = []script{
	{"hash-basics", []step{
		cmd("HSET", "h", "f1", "v1", "f2", "v2", "f3", "v3"),
		cmd("HGET", "h", "f1"),
		cmd("HGET", "h", "nofield"),
		cmd("HGET", "nokey", "f"),
		cmd("HSET", "h", "f1", "v1b"), // update: 0 new
		cmd("HGET", "h", "f1"),
		cmd("HLEN", "h"),
		cmd("HLEN", "nokey"),
		cmd("HEXISTS", "h", "f2"),
		cmd("HEXISTS", "h", "no"),
		cmd("HEXISTS", "nokey", "f"),
		cmd("HKEYS", "h"),   // insertion order (listpack)
		cmd("HVALS", "h"),   // insertion order
		cmd("HGETALL", "h"), // insertion order
		cmd("HGETALL", "nokey"),
		cmd("HKEYS", "nokey"),
		cmd("HSETNX", "h", "f1", "x"),
		cmd("HSETNX", "h", "f4", "v4"),
		cmd("HGET", "h", "f4"),
		cmd("HSETNX", "nokey2", "f", "v"),
		cmd("TYPE", "nokey2"),
		cmd("HSTRLEN", "h", "f1"),
		cmd("HSTRLEN", "h", "no"),
		cmd("HSTRLEN", "nokey", "f"),
		cmd("HMSET", "hm", "a", "1", "b", "2"),
		cmd("HMGET", "hm", "a", "b", "no"),
		cmd("HMGET", "nokey", "a", "b"),
		cmd("HDEL", "h", "f1", "no", "f2"),
		cmd("HGETALL", "h"), // f3 f4 remain, insertion order
		cmd("HDEL", "h", "f3", "f4"),
		cmd("EXISTS", "h"), // emptied: key gone
		cmd("TYPE", "h"),
		cmd("HDEL", "nokey", "f"),
		// re-add after delete goes to the end (listpack order)
		cmd("HSET", "h2", "z", "1", "a", "2", "m", "3"),
		cmd("HDEL", "h2", "z"),
		cmd("HSET", "h2", "z", "5"),
		cmd("HGETALL", "h2"),
		// empty value and empty field
		cmd("HSET", "h3", "", ""),
		cmd("HGETALL", "h3"),
		cmd("HSTRLEN", "h3", ""),
	}},
	{"hash-errors", []step{
		cmd("SET", "str", "v"),
		cmd("HSET", "str", "f", "v"),
		cmd("HGET", "str", "f"),
		cmd("HMGET", "str", "f"),
		cmd("HGETALL", "str"),
		cmd("HDEL", "str", "f"),
		cmd("HEXISTS", "str", "f"),
		cmd("HLEN", "str"),
		cmd("HKEYS", "str"),
		cmd("HVALS", "str"),
		cmd("HSTRLEN", "str", "f"),
		cmd("HSETNX", "str", "f", "v"),
		cmd("HINCRBY", "str", "f", "1"),
		cmd("HINCRBYFLOAT", "str", "f", "1"),
		cmd("HRANDFIELD", "str"),
		cmd("HSCAN", "str", "0"),
		// arity
		cmd("HSET", "h", "f"),
		cmd("HMSET", "hm", "a", "1", "b"),
		cmd("HGET", "h"),
		cmd("HGET", "h", "f", "extra"),
		cmd("HGETALL", "h", "x"),
		cmd("HDEL", "h"),
		cmd("HSCAN", "h"),
		cmd("HSCAN", "h", "abc"),
		cmd("HSCAN", "h", "0", "COUNT", "0"),
		cmd("HSCAN", "h", "0", "COUNT", "abc"),
		cmd("HSCAN", "h", "0", "COUNT", "5", "MATCH"),
		cmd("HSCAN", "h", "0", "BADOPT"),
		cmd("HSCAN", "nokey", "0"),
	}},
	{"hash-incr", []step{
		cmd("HINCRBY", "h", "n", "5"),
		cmd("HINCRBY", "h", "n", "-2"),
		cmd("HGET", "h", "n"),
		cmd("HSET", "h", "bad", "abc"),
		cmd("HINCRBY", "h", "bad", "1"),
		cmd("HSET", "h", "float", "1.5"),
		cmd("HINCRBY", "h", "float", "1"),
		cmd("HINCRBY", "h", "n", "abc"),
		cmd("HINCRBY", "h", "n", "1.5"),
		cmd("HSET", "h", "max", "9223372036854775807"),
		cmd("HINCRBY", "h", "max", "1"),
		cmd("HINCRBY", "h", "max", "-1"),
		cmd("HSET", "h", "min", "-9223372036854775808"),
		cmd("HINCRBY", "h", "min", "-1"),
		cmd("HINCRBYFLOAT", "h", "f", "1.1"),
		cmd("HINCRBYFLOAT", "h", "f", "1.1"),
		cmd("HGET", "h", "f"),
		cmd("HINCRBYFLOAT", "h", "g", "0.3"),
		cmd("HINCRBYFLOAT", "h", "g", "0.3"),
		cmd("HINCRBYFLOAT", "h", "i", "5"),
		cmd("HINCRBYFLOAT", "h", "i", "3e3"),
		cmd("HINCRBYFLOAT", "h", "i", ".5"),
		cmd("HINCRBYFLOAT", "h", "i", "0x10"),
		cmd("HINCRBYFLOAT", "h", "bad", "1"),
		cmd("HINCRBYFLOAT", "h", "f", "nan"),
		cmd("HINCRBYFLOAT", "h", "f", "inf"),
		cmd("HINCRBYFLOAT", "h", "f", "-inf"),
		cmd("HINCRBYFLOAT", "h", "f", "1e9999"),
		cmd("HINCRBYFLOAT", "h", "f", "1e-9999"),
		cmd("HINCRBYFLOAT", "h", "big", "1.7976931348623157e308"),
		cmd("HINCRBYFLOAT", "h", "big", "1e308"),
		cmd("HGET", "h", "big"),
		cmd("HINCRBYFLOAT", "h", "tiny", "1e-20"), // rounds to "0" at 17 digits
		cmd("HINCRBYFLOAT", "h", "e", "1e300"),
		cmd("HGET", "h", "e"),
	}},
	{"hash-randfield", []step{
		cmd("HRANDFIELD", "nokey"),
		cmd("HRANDFIELD", "nokey", "3"),
		cmd("HRANDFIELD", "nokey", "-3"),
		cmd("HRANDFIELD", "nokey", "3", "WITHVALUES"),
		cmd("HRANDFIELD", "nokey", "abc"),
		cmd("HRANDFIELD", "nokey", "1", "BADOPT"),
		cmd("HRANDFIELD", "nokey", "1", "WITHVALUES", "EXTRA"),
		cmd("HRANDFIELD", "nokey", "WITHVALUES"),
		cmd("HSET", "h", "only", "v"),
		cmd("HRANDFIELD", "h"),
		cmd("HRANDFIELD", "h", "1"),
		cmd("HRANDFIELD", "h", "5"),
		cmd("HRANDFIELD", "h", "-3"),
		cmd("HRANDFIELD", "h", "-3", "WITHVALUES"),
		cmd("HRANDFIELD", "h", "0"),
		// count >= size: every field, insertion order, unshuffled
		cmd("HSET", "h2", "a", "1", "b", "2", "c", "3"),
		cmd("HRANDFIELD", "h2", "10"),
		cmd("HRANDFIELD", "h2", "10", "WITHVALUES"),
	}},
	{"hash-scan", []step{
		cmd("HSET", "h", "a", "1", "b", "2", "c", "3", "d", "4"),
		cmdM(mScanAllPairs, "HSCAN", "h", "0", "COUNT", "1000"),
		cmdM(mScanAllPairs, "HSCAN", "h", "0", "MATCH", "[ab]", "COUNT", "1000"),
		cmdM(mScanAllPairs, "HSCAN", "h", "0", "MATCH", "nada*"),
		cmdM(mScanAllPairs, "HSCAN", "nokey", "0"),
		{args: []string{"HSCANLOOP", "h"}, m: mEq},
	}},
	{"hash-promotion", func() []step {
		// Cross hash-max-listpack-entries (128): 129 fields promote to the
		// large encoding. Wire-visible behavior must stay exact.
		steps := []step{}
		pairs := []string{}
		for i := 0; i < 129; i++ {
			pairs = append(pairs, "f"+itoa(i), "v"+itoa(i))
		}
		steps = append(steps, cmd(append([]string{"HSET", "big"}, pairs...)...))
		steps = append(steps,
			cmd("HLEN", "big"),
			cmd("HGET", "big", "f0"),
			cmd("HGET", "big", "f128"),
			cmdM(mPairCmp, "HGETALL", "big"),
			cmdM(mScanAllPairs, "HSCAN", "big", "0", "COUNT", "1000"),
			step{args: []string{"HSCANLOOP", "big"}, m: mEq},
			cmd("HDEL", "big", "f0", "f1", "f2"),
			cmd("HLEN", "big"),
			cmdM(mPairCmp, "HGETALL", "big"),
		)
		return steps
	}()},
	{"hash-expiry", []step{
		cmd("HSET", "hx", "f", "v"),
		cmd("PEXPIRE", "hx", "150"),
		cmdM(mTTL, "PTTL", "hx"),
		cmd("HGET", "hx", "f"),
		cmd("SLEEP", "250"),
		cmd("HGET", "hx", "f"),
		cmd("EXISTS", "hx"),
		cmd("HSET", "hx", "f", "v"),
		cmd("TTL", "hx"), // recreated without TTL
	}},
}

var p1ListScripts = []script{
	{"list-basics", []step{
		cmd("LPUSH", "l", "a", "b", "c"),
		cmd("LRANGE", "l", "0", "-1"),
		cmd("RPUSH", "l", "d", "e"),
		cmd("LRANGE", "l", "0", "-1"),
		cmd("LLEN", "l"),
		cmd("LLEN", "nokey"),
		cmd("TYPE", "l"),
		cmd("LRANGE", "nokey", "0", "-1"),
		cmd("LRANGE", "l", "1", "3"),
		cmd("LRANGE", "l", "-2", "-1"),
		cmd("LRANGE", "l", "0", "-99"),
		cmd("LRANGE", "l", "-99", "-98"),
		cmd("LRANGE", "l", "2", "1"),
		cmd("LRANGE", "l", "5", "10"),
		cmd("LINDEX", "l", "0"),
		cmd("LINDEX", "l", "-1"),
		cmd("LINDEX", "l", "99"),
		cmd("LINDEX", "l", "-99"),
		cmd("LINDEX", "nokey", "0"),
		cmd("LPUSHX", "nokey", "x"),
		cmd("RPUSHX", "nokey", "x"),
		cmd("LPUSHX", "l", "h1", "h2"),
		cmd("RPUSHX", "l", "t1"),
		cmd("LRANGE", "l", "0", "-1"),
	}},
	{"list-pop", []step{
		cmd("LPOP", "nokey"),
		cmd("RPOP", "nokey", "2"),
		cmd("LPOP", "nokey", "0"),
		cmd("RPUSH", "l", "a", "b", "c", "d"),
		cmd("LPOP", "l"),
		cmd("RPOP", "l"),
		cmd("LPOP", "l", "0"),
		cmd("LLEN", "l"),
		cmd("LPOP", "l", "5"),
		cmd("EXISTS", "l"),
		cmd("RPUSH", "l", "x"),
		cmd("RPOP", "l", "1"),
		cmd("EXISTS", "l"),
		cmd("RPUSH", "l", "a", "b"),
		cmd("LPOP", "l", "abc"),
		cmd("LPOP", "l", "-1"),
		cmd("RPOP", "l", "-0"),
		cmd("LPOP", "l", "1", "EXTRA"),
	}},
	{"list-set-insert-rem", []step{
		cmd("RPUSH", "l", "a", "b", "c", "b", "d"),
		cmd("LSET", "l", "0", "A"),
		cmd("LSET", "l", "-1", "D"),
		cmd("LRANGE", "l", "0", "-1"),
		cmd("LSET", "l", "5", "x"),
		cmd("LSET", "l", "-6", "x"),
		cmd("LSET", "nokey", "0", "x"),
		cmd("LSET", "l", "abc", "x"),
		cmd("LINSERT", "l", "BEFORE", "b", "X"),
		cmd("LINSERT", "l", "AFTER", "b", "Y"),
		cmd("LRANGE", "l", "0", "-1"),
		cmd("LINSERT", "l", "BEFORE", "nomatch", "Z"),
		cmd("LINSERT", "nokey", "BEFORE", "a", "Z"),
		cmd("LINSERT", "l", "BAD", "b", "Z"),
		cmd("LREM", "l", "1", "b"),
		cmd("LRANGE", "l", "0", "-1"),
		cmd("RPUSH", "l", "b", "b", "b"),
		cmd("LREM", "l", "-2", "b"),
		cmd("LRANGE", "l", "0", "-1"),
		cmd("LREM", "l", "0", "b"),
		cmd("LRANGE", "l", "0", "-1"),
		cmd("LREM", "l", "0", "nomatch"),
		cmd("LREM", "nokey", "0", "x"),
		cmd("LREM", "l", "abc", "x"),
		cmd("LREM", "l", "0", "X"),
		cmd("LREM", "l", "0", "Y"),
		cmd("LREM", "l", "0", "A"),
		cmd("LREM", "l", "0", "c"),
		cmd("LREM", "l", "0", "D"),
		cmd("EXISTS", "l"), // all removed: key gone
	}},
	{"list-trim", []step{
		cmd("LTRIM", "nokey", "0", "-1"),
		cmd("RPUSH", "l", "a", "b", "c", "d", "e"),
		cmd("LTRIM", "l", "1", "3"),
		cmd("LRANGE", "l", "0", "-1"),
		cmd("LTRIM", "l", "-2", "-1"),
		cmd("LRANGE", "l", "0", "-1"),
		cmd("LTRIM", "l", "5", "10"),
		cmd("EXISTS", "l"),
		cmd("RPUSH", "l", "a"),
		cmd("LTRIM", "l", "-1", "0"),
		cmd("EXISTS", "l"),
		cmd("LTRIM", "l", "abc", "0"),
	}},
	{"list-move", []step{
		cmd("RPOPLPUSH", "nokey", "dst"),
		cmd("RPUSH", "src", "a", "b", "c"),
		cmd("RPOPLPUSH", "src", "dst"),
		cmd("LRANGE", "src", "0", "-1"),
		cmd("LRANGE", "dst", "0", "-1"),
		cmd("LMOVE", "src", "dst", "LEFT", "RIGHT"),
		cmd("LMOVE", "src", "dst", "LEFT", "LEFT"),
		cmd("LRANGE", "src", "0", "-1"),
		cmd("LRANGE", "dst", "0", "-1"),
		cmd("LMOVE", "src", "dst", "BAD", "LEFT"),
		cmd("LMOVE", "src", "dst", "LEFT", "BAD"),
		// same-key rotation
		cmd("LMOVE", "dst", "dst", "LEFT", "RIGHT"),
		cmd("LRANGE", "dst", "0", "-1"),
		cmd("RPOPLPUSH", "dst", "dst"),
		cmd("LRANGE", "dst", "0", "-1"),
		cmd("LMOVE", "dst", "dst", "LEFT", "LEFT"),
		cmd("LMOVE", "dst", "dst", "RIGHT", "RIGHT"),
		cmd("LRANGE", "dst", "0", "-1"),
		// drain src entirely
		cmd("RPOPLPUSH", "src", "dst"),
		cmd("EXISTS", "src"),
		// wrong types
		cmd("SET", "str", "v"),
		cmd("RPOPLPUSH", "str", "dst"),
		cmd("RPOPLPUSH", "dst", "str"),
		cmd("LLEN", "dst"),                            // unchanged
		cmd("LMOVE", "nokey", "str", "LEFT", "RIGHT"), // missing src: null wins? no — dst type checked
		cmd("LMOVE", "nokey", "dst", "LEFT", "RIGHT"),
	}},
	{"list-pos", []step{
		cmd("LPOS", "nokey", "x"),
		cmd("LPOS", "nokey", "x", "COUNT", "2"),
		cmd("RPUSH", "l", "a", "b", "c", "b", "a"),
		cmd("LPOS", "l", "b"),
		cmd("LPOS", "l", "b", "RANK", "2"),
		cmd("LPOS", "l", "b", "RANK", "-1"),
		cmd("LPOS", "l", "b", "RANK", "-2"),
		cmd("LPOS", "l", "b", "RANK", "3"),
		cmd("LPOS", "l", "b", "RANK", "0"),
		cmd("LPOS", "l", "nomatch"),
		cmd("LPOS", "l", "b", "COUNT", "0"),
		cmd("LPOS", "l", "b", "COUNT", "1"),
		cmd("LPOS", "l", "b", "RANK", "-1", "COUNT", "2"),
		cmd("LPOS", "l", "b", "COUNT", "0", "MAXLEN", "2"),
		cmd("LPOS", "l", "b", "RANK", "-1", "MAXLEN", "1"),
		cmd("LPOS", "l", "b", "COUNT", "-1"),
		cmd("LPOS", "l", "b", "COUNT", "abc"),
		cmd("LPOS", "l", "b", "MAXLEN", "-1"),
		cmd("LPOS", "l", "b", "MAXLEN", "abc"),
		cmd("LPOS", "l", "b", "RANK", "abc"),
		cmd("LPOS", "l", "b", "BADOPT", "1"),
		cmd("LPOS", "l"),
	}},
	{"list-errors", []step{
		cmd("SET", "str", "v"),
		cmd("LPUSH", "str", "x"),
		cmd("RPUSH", "str", "x"),
		cmd("LPUSHX", "str", "x"),
		cmd("RPUSHX", "str", "x"),
		cmd("LPOP", "str"),
		cmd("RPOP", "str", "1"),
		cmd("LLEN", "str"),
		cmd("LRANGE", "str", "0", "-1"),
		cmd("LINDEX", "str", "0"),
		cmd("LSET", "str", "0", "x"),
		cmd("LINSERT", "str", "BEFORE", "a", "b"),
		cmd("LREM", "str", "0", "x"),
		cmd("LTRIM", "str", "0", "-1"),
		cmd("LPOS", "str", "x"),
		cmd("RPOPLPUSH", "str", "other"),
		cmd("LMOVE", "str", "other", "LEFT", "RIGHT"),
		cmd("LMOVE", "other", "str", "LEFT", "RIGHT"),
		cmd("LRANGE", "l", "abc", "0"),
		cmd("LRANGE", "l", "0", "1.5"),
		cmd("LINDEX", "l", "abc"),
	}},
	{"list-large", func() []step {
		elems := []string{}
		for i := 0; i < 500; i++ {
			elems = append(elems, "e"+itoa(i))
		}
		steps := []step{cmd(append([]string{"RPUSH", "big"}, elems...)...)}
		steps = append(steps,
			cmd("LLEN", "big"),
			cmd("LRANGE", "big", "0", "9"),
			cmd("LRANGE", "big", "-5", "-1"),
			cmd("LRANGE", "big", "250", "260"),
			cmd("LINDEX", "big", "499"),
			cmd("LTRIM", "big", "100", "399"),
			cmd("LLEN", "big"),
			cmd("LINDEX", "big", "0"),
			cmd("LINDEX", "big", "-1"),
			cmd("LPOP", "big", "300"),
			cmd("EXISTS", "big"),
		)
		return steps
	}()},
}

var p1SetScripts = []script{
	{"set-basics", []step{
		cmd("SADD", "s", "3", "1", "2"),
		cmd("SMEMBERS", "s"),       // intset: sorted numerically
		cmd("SADD", "s", "2", "4"), // one dup
		cmd("SCARD", "s"),
		cmd("SISMEMBER", "s", "3"),
		cmd("SISMEMBER", "s", "9"),
		cmd("SISMEMBER", "nokey", "1"),
		cmd("SMISMEMBER", "s", "1", "9", "4"),
		cmd("SMISMEMBER", "nokey", "a"),
		cmd("TYPE", "s"),
		cmd("SREM", "s", "1", "9"),
		cmd("SMEMBERS", "s"),
		cmd("SREM", "s", "2", "3", "4"),
		cmd("EXISTS", "s"),
		cmd("SREM", "nokey", "a"),
		// negative ints and int formatting
		cmd("SADD", "si", "-5", "10", "-100", "0"),
		cmd("SMEMBERS", "si"),
		// non-int promotes to hashtable encoding
		cmd("SADD", "sm", "1", "2", "x"),
		cmdM(mSetCmp, "SMEMBERS", "sm"),
		cmd("SISMEMBER", "sm", "x"),
		// "01" is not an int (string2ll): promotes too
		cmd("SADD", "s01", "01"),
		cmd("SISMEMBER", "s01", "1"),
		cmdM(mSetCmp, "SMEMBERS", "s01"),
		// empty member
		cmd("SADD", "se", ""),
		cmd("SMEMBERS", "se"),
	}},
	{"set-errors", []step{
		cmd("SET", "str", "v"),
		cmd("SADD", "str", "a"),
		cmd("SREM", "str", "a"),
		cmd("SMEMBERS", "str"),
		cmd("SISMEMBER", "str", "a"),
		cmd("SMISMEMBER", "str", "a"),
		cmd("SCARD", "str"),
		cmd("SPOP", "str"),
		cmd("SPOP", "str", "1"),
		cmd("SRANDMEMBER", "str"),
		cmd("SMOVE", "str", "s2", "a"),
		cmd("SMOVE", "s2", "str", "a"),
		cmd("SINTER", "str", "s2"),
		cmd("SUNION", "str"),
		cmd("SDIFF", "str", "s2"),
		cmd("SINTERSTORE", "d", "str", "s2"),
		cmd("SUNIONSTORE", "d", "str"),
		cmd("SDIFFSTORE", "d", "s2", "str"),
		cmd("SINTERCARD", "1", "str"),
		cmd("SSCAN", "str", "0"),
		cmd("SADD", "s"),
		cmd("SREM", "s"),
		cmd("SISMEMBER", "s"),
		cmd("SPOP", "s", "-1"),
		cmd("SPOP", "s", "abc"),
		cmd("SRANDMEMBER", "s", "abc"),
		cmd("SMOVE", "a", "b"),
		cmd("SINTER"),
		cmd("SINTERSTORE", "d"),
		cmd("SINTERCARD"),
		cmd("SINTERCARD", "0", "s"),
		cmd("SINTERCARD", "abc", "s"),
		cmd("SINTERCARD", "3", "s", "s2"),
		cmd("SINTERCARD", "2", "s", "s2", "LIMIT", "-1"),
		cmd("SINTERCARD", "2", "s", "s2", "LIMIT", "abc"),
		cmd("SINTERCARD", "2", "s", "s2", "BADOPT", "1"),
		cmd("SINTERCARD", "2", "s", "s2", "LIMIT", "1", "EXTRA"),
	}},
	{"set-pop-rand", []step{
		cmd("SPOP", "nokey"),
		cmd("SPOP", "nokey", "3"),
		cmd("SPOP", "nokey", "0"),
		cmd("SRANDMEMBER", "nokey"),
		cmd("SRANDMEMBER", "nokey", "3"),
		cmd("SRANDMEMBER", "nokey", "-3"),
		cmd("SRANDMEMBER", "nokey", "0"),
		cmd("SADD", "one", "x"),
		cmd("SPOP", "one"),
		cmd("EXISTS", "one"),
		cmd("SADD", "one", "x"),
		cmd("SPOP", "one", "1"),
		cmd("EXISTS", "one"),
		cmd("SADD", "one", "x"),
		cmd("SPOP", "one", "5"), // count >= card: all, key deleted
		cmd("EXISTS", "one"),
		cmd("SADD", "s", "1", "2", "3"),
		cmd("SPOP", "s", "99"),
		cmd("EXISTS", "s"),
		cmd("SADD", "s", "1", "2", "3"),
		cmd("SPOP", "s", "0"),
		cmd("SCARD", "s"),
		cmdM(mAnyArr, "SPOP", "s", "2"), // random picks; only the shape is stable
		cmd("SCARD", "s"),
		cmd("SADD", "s", "1", "2", "3"),
		cmd("SRANDMEMBER", "s", "99"), // all, intset order
		cmd("SADD", "one2", "y"),
		cmd("SRANDMEMBER", "one2"),
		cmd("SRANDMEMBER", "one2", "-3"), // repetition on singleton
	}},
	{"set-move", []step{
		cmd("SMOVE", "nokey", "dst", "a"),
		cmd("SADD", "src", "a", "b", "c"),
		cmd("SMOVE", "src", "dst", "z"),
		cmd("SMOVE", "src", "dst", "b"),
		cmdM(mSetCmp, "SMEMBERS", "src"),
		cmdM(mSetCmp, "SMEMBERS", "dst"),
		cmd("TYPE", "dst"),
		cmd("SMOVE", "src", "src", "a"), // same key: no-op, 1
		cmd("SMOVE", "src", "src", "zz"),
		cmdM(mSetCmp, "SMEMBERS", "src"),
		cmd("SMOVE", "src", "dst", "a"),
		cmd("SMOVE", "src", "dst", "c"),
		cmd("EXISTS", "src"),
		cmdM(mSetCmp, "SMEMBERS", "dst"),
		// move onto existing member
		cmd("SADD", "src", "b"),
		cmd("SMOVE", "src", "dst", "b"),
		cmd("SCARD", "dst"),
	}},
	{"set-algebra", []step{
		cmd("SADD", "a", "1", "2", "3", "5", "7"),
		cmd("SADD", "b", "2", "5", "4"),
		cmd("SINTER", "a", "b"),
		cmd("SUNION", "a", "b"),
		cmd("SDIFF", "a", "b"),
		cmd("SDIFF", "b", "a"),
		cmd("SINTER", "a", "nokey"),
		cmd("SINTER", "nokey", "nokey2"),
		cmd("SUNION", "nokey", "nokey2"),
		cmd("SDIFF", "nokey", "a"),
		cmd("SINTER", "a"),
		cmd("SINTER", "a", "b", "a"),
		// mixed (hashtable) sets: unordered
		cmd("SADD", "x", "a", "b", "c"),
		cmd("SADD", "y", "b", "c", "d"),
		cmdM(mSetCmp, "SINTER", "x", "y"),
		cmdM(mSetCmp, "SUNION", "x", "y"),
		cmdM(mSetCmp, "SDIFF", "x", "y"),
		cmdM(mSetCmp, "SDIFF", "y", "x"),
		// stores
		cmd("SINTERSTORE", "d", "a", "b"),
		cmd("SMEMBERS", "d"),
		cmd("SUNIONSTORE", "d", "a", "b"),
		cmd("SMEMBERS", "d"),
		cmd("SDIFFSTORE", "d", "a", "b"),
		cmd("SMEMBERS", "d"),
		cmd("SINTERSTORE", "d", "a", "nokey"), // empty: dest deleted
		cmd("EXISTS", "d"),
		cmd("SINTERSTORE", "d", "x", "y"),
		cmdM(mSetCmp, "SMEMBERS", "d"),
		// store over a string key replaces it
		cmd("SET", "dstr", "v"),
		cmd("SUNIONSTORE", "dstr", "a", "b"),
		cmd("TYPE", "dstr"),
		cmd("SMEMBERS", "dstr"),
		// dest is also a source
		cmd("SINTERSTORE", "a", "a", "b"),
		cmd("SMEMBERS", "a"),
		// intset stays sorted through stores
		cmd("SADD", "p", "9", "3", "5"),
		cmd("SADD", "q", "5", "9", "1"),
		cmd("SINTERSTORE", "d2", "p", "q"),
		cmd("SMEMBERS", "d2"),
		cmd("SUNIONSTORE", "d2", "p", "q"),
		cmd("SMEMBERS", "d2"),
	}},
	{"set-intercard", []step{
		cmd("SADD", "a", "1", "2", "3", "5", "7"),
		cmd("SADD", "b", "2", "5", "4"),
		cmd("SINTERCARD", "2", "a", "b"),
		cmd("SINTERCARD", "2", "a", "b", "LIMIT", "1"),
		cmd("SINTERCARD", "2", "a", "b", "LIMIT", "0"),
		cmd("SINTERCARD", "1", "a"),
		cmd("SINTERCARD", "3", "a", "b", "nokey"),
		cmd("SINTERCARD", "2", "a", "a"),
		cmd("SADD", "x", "a", "b"),
		cmd("SADD", "y", "b", "c"),
		cmd("SINTERCARD", "2", "x", "y"),
		cmd("SINTERCARD", "2", "x", "y", "LIMIT", "1"),
	}},
	{"set-scan", []step{
		cmd("SADD", "s", "a", "b", "c", "1", "2", "3"),
		cmdM(mScanAll, "SSCAN", "s", "0", "COUNT", "1000"),
		cmdM(mScanAll, "SSCAN", "s", "0", "MATCH", "[abc]", "COUNT", "1000"),
		cmdM(mScanAll, "SSCAN", "s", "0", "MATCH", "nada*"),
		cmdM(mScanAll, "SSCAN", "nokey", "0"),
		{args: []string{"SSCANLOOP", "s"}, m: mEq},
		cmd("SSCAN", "s", "abc"),
		cmd("SSCAN", "s", "0", "COUNT", "0"),
	}},
	{"set-intset-promotion", func() []step {
		// Past set-max-intset-entries (512) the encoding flips to the
		// hashtable; membership semantics must stay exact.
		members := []string{}
		for i := 0; i < 513; i++ {
			members = append(members, strconv.Itoa(i*3))
		}
		steps := []step{cmd(append([]string{"SADD", "big"}, members...)...)}
		steps = append(steps,
			cmd("SCARD", "big"),
			cmd("SISMEMBER", "big", "0"),
			cmd("SISMEMBER", "big", "1536"),
			cmd("SISMEMBER", "big", "1"),
			cmdM(mSetCmp, "SMEMBERS", "big"),
			cmdM(mScanAll, "SSCAN", "big", "0", "COUNT", "5000"),
			cmd("SREM", "big", "0", "3", "6"),
			cmd("SCARD", "big"),
			cmd("SADD", "big", "notanint"),
			cmd("SISMEMBER", "big", "notanint"),
			cmd("SCARD", "big"),
		)
		return steps
	}()},
}

var p1ZSetScripts = []script{
	{"zset-add", []step{
		cmd("ZADD", "z", "1", "a", "2", "b", "3", "c"),
		cmd("ZADD", "z", "5", "a"), // update: 0 new
		cmd("ZSCORE", "z", "a"),
		cmd("ZADD", "z", "CH", "4", "a", "9", "d"), // 1 changed + 1 new
		cmd("ZADD", "z", "XX", "10", "b"),
		cmd("ZSCORE", "z", "b"),
		cmd("ZADD", "z", "XX", "1", "noexist"),
		cmd("ZADD", "z", "NX", "1", "b"), // exists: refused
		cmd("ZSCORE", "z", "b"),
		cmd("ZADD", "z", "NX", "7", "new"),
		cmd("ZSCORE", "z", "new"),
		cmd("ZADD", "z", "GT", "100", "b"),
		cmd("ZSCORE", "z", "b"),
		cmd("ZADD", "z", "GT", "1", "b"),
		cmd("ZSCORE", "z", "b"),
		cmd("ZADD", "z", "LT", "50", "b"),
		cmd("ZSCORE", "z", "b"),
		cmd("ZADD", "z", "LT", "100", "b"),
		cmd("ZSCORE", "z", "b"),
		cmd("ZADD", "z", "GT", "5", "brand-new"), // GT adds new elements
		cmd("ZADD", "z", "LT", "3", "brand-new"),
		cmd("ZSCORE", "z", "brand-new"),
		cmd("ZADD", "z", "GT", "1", "another-new"),
		cmd("ZSCORE", "z", "another-new"),
		cmd("ZADD", "z", "XX", "GT", "200", "b"),
		cmd("ZSCORE", "z", "b"),
		// score syntax
		cmd("ZADD", "z", "+1.5e3", "sci"),
		cmd("ZSCORE", "z", "sci"),
		cmd("ZADD", "z", "01", "lead"),
		cmd("ZSCORE", "z", "lead"),
		cmd("ZADD", "z", ".5", "half"),
		cmd("ZSCORE", "z", "half"),
		cmd("ZADD", "z", "1.", "dot"),
		cmd("ZADD", "z", "0x10", "hex"),
		cmd("ZSCORE", "z", "hex"),
		cmd("ZADD", "z", "inf", "pinf"),
		cmd("ZADD", "z", "-INF", "ninf"),
		cmd("ZADD", "z", "Infinity", "pinf2"),
		cmd("ZSCORE", "z", "pinf"),
		cmd("ZSCORE", "z", "ninf"),
		cmd("ZADD", "z", "nan", "bad"),
		cmd("ZADD", "z", "NaN", "bad"),
		cmd("ZADD", "z", "1.5.2", "bad"),
		cmd("ZADD", "z", "abc", "bad"),
		cmd("ZADD", "z", "", "bad"),
		cmd("ZADD", "z", "1e9999", "bad"),
		cmd("ZADD", "z", "1e-9999", "bad"),
		cmd("ZADD", "z", "1_0", "bad"),
		// option errors
		cmd("ZADD", "z", "NX", "XX", "1", "a"),
		cmd("ZADD", "z", "GT", "LT", "1", "a"),
		cmd("ZADD", "z", "GT", "NX", "1", "a"),
		cmd("ZADD", "z", "LT", "NX", "1", "a"),
		cmd("ZADD", "z", "BADOPT", "1", "a"),
		cmd("ZADD", "z", "1", "a", "2"),
		cmd("ZADD", "z", "INCR", "1", "a", "2", "b"),
		cmd("ZADD", "z", "INCR", "1", "a", "CH"),
		cmd("ZADD", "z"),
		// wrong type
		cmd("SET", "str", "v"),
		cmd("ZADD", "str", "1", "a"),
	}},
	{"zset-incr", []step{
		cmd("ZINCRBY", "z", "5", "m"),
		cmd("ZINCRBY", "z", "0.5", "m"),
		cmd("ZSCORE", "z", "m"),
		cmd("ZINCRBY", "z", "-1.5", "m"),
		cmd("ZSCORE", "z", "m"),
		cmd("ZINCRBY", "z", "2.5e1", "e"),
		cmd("ZSCORE", "z", "e"),
		cmd("ZINCRBY", "z", "inf", "m"),
		cmd("ZSCORE", "z", "m"),
		cmd("ZINCRBY", "z", "-inf", "m"), // inf + -inf = NaN
		cmd("ZSCORE", "z", "m"),
		cmd("ZINCRBY", "z", "nan", "x"),
		cmd("ZINCRBY", "z", "1e9999", "x"),
		cmd("ZINCRBY", "z", "abc", "x"),
		cmd("ZADD", "z2", "INCR", "5", "m"),
		cmd("ZADD", "z2", "INCR", "2.5", "m"),
		cmd("ZSCORE", "z2", "m"),
		cmd("ZADD", "z2", "INCR", "XX", "5", "nope"),
		cmd("ZADD", "z2", "INCR", "NX", "5", "m"),
		cmd("ZSCORE", "z2", "m"),
		cmd("ZADD", "z2", "INCR", "GT", "100", "m"),
		cmd("ZADD", "z2", "INCR", "GT", "0.5", "m"),
		cmd("ZSCORE", "z2", "m"),
	}},
	{"zset-score-mscore", []step{
		cmd("ZSCORE", "nokey", "m"),
		cmd("ZADD", "z", "0.1", "x", "2", "y", "1e17", "big", "1e21", "huge", "1e-5", "tiny"),
		cmd("ZADD", "z", "1e-7", "tinier", "100000", "k100", "123456789012345", "long"),
		cmd("ZSCORE", "z", "x"),
		cmd("ZSCORE", "z", "y"),
		cmd("ZSCORE", "z", "big"),
		cmd("ZSCORE", "z", "huge"),
		cmd("ZSCORE", "z", "tiny"),
		cmd("ZSCORE", "z", "tinier"),
		cmd("ZSCORE", "z", "k100"),
		cmd("ZSCORE", "z", "long"),
		cmd("ZMSCORE", "z", "x", "nope", "y"),
		cmd("ZMSCORE", "nokey", "x", "y"),
		cmd("ZMSCORE", "z"),
		cmd("ZADD", "z", "-0", "negzero"),
		cmd("ZSCORE", "z", "negzero"),
	}},
	{"zset-rank", []step{
		cmd("ZRANK", "nokey", "a"),
		cmd("ZADD", "z", "1", "a", "2", "b", "3", "c"),
		cmd("ZRANK", "z", "a"),
		cmd("ZRANK", "z", "c"),
		cmd("ZREVRANK", "z", "a"),
		cmd("ZREVRANK", "z", "c"),
		cmd("ZRANK", "z", "no"),
		cmd("ZRANK", "z", "b", "WITHSCORE"),
		cmd("ZREVRANK", "z", "b", "WITHSCORE"),
		cmd("ZRANK", "z", "no", "WITHSCORE"),
		cmd("ZRANK", "nokey", "a", "WITHSCORE"),
		cmd("ZRANK", "z", "a", "WITHSCORES"),
		cmd("ZRANK", "z", "a", "BADOPT"),
		cmd("ZRANK", "z"),
	}},
	{"zset-range-index", []step{
		cmd("ZADD", "z", "1", "a", "2", "b", "3", "c", "4", "d", "5", "e"),
		cmd("ZRANGE", "z", "0", "-1"),
		cmd("ZRANGE", "z", "1", "3"),
		cmd("ZRANGE", "z", "-2", "-1"),
		cmd("ZRANGE", "z", "0", "-99"),
		cmd("ZRANGE", "z", "3", "2"),
		cmd("ZRANGE", "z", "10", "20"),
		cmd("ZRANGE", "z", "0", "-1", "WITHSCORES"),
		cmd("ZRANGE", "z", "0", "-1", "REV"),
		cmd("ZRANGE", "z", "-1", "0", "REV"),
		cmd("ZRANGE", "z", "1", "3", "REV", "WITHSCORES"),
		cmd("ZREVRANGE", "z", "0", "-1"),
		cmd("ZREVRANGE", "z", "1", "2", "WITHSCORES"),
		cmd("ZRANGE", "nokey", "0", "-1"),
		cmd("ZRANGE", "nokey", "0", "-1", "REV"),
		cmd("ZRANGE", "nokey", "abc", "-1"),
		cmd("ZRANGE", "z", "abc", "-1"),
		cmd("ZRANGE", "z", "0", "abc"),
		cmd("ZRANGE", "z", "0", "-1", "BADOPT"),
		cmd("ZRANGE", "z", "0", "-1", "BYSCORE", "BYLEX"),
		cmd("ZRANGE", "z", "0", "-1", "WITHSCORES", "LIMIT", "0", "1"),
		cmd("ZRANGE", "z", "0", "-1", "LIMIT", "0", "1"),
		// equal scores order by member bytes
		cmd("ZADD", "zeq", "1", "banana", "1", "apple", "1", "cherry"),
		cmd("ZRANGE", "zeq", "0", "-1"),
	}},
	{"zset-range-byscore", []step{
		cmd("ZADD", "z", "1", "a", "2", "b", "3", "c", "4", "d", "5", "e"),
		cmd("ZRANGEBYSCORE", "z", "1", "3"),
		cmd("ZRANGEBYSCORE", "z", "(1", "3"),
		cmd("ZRANGEBYSCORE", "z", "1", "(3"),
		cmd("ZRANGEBYSCORE", "z", "(1", "(3"),
		cmd("ZRANGEBYSCORE", "z", "-inf", "+inf"),
		cmd("ZRANGEBYSCORE", "z", "inf", "+inf"),
		cmd("ZRANGEBYSCORE", "z", "3", "1"),
		cmd("ZRANGEBYSCORE", "z", "2", "4", "LIMIT", "1", "1"),
		cmd("ZRANGEBYSCORE", "z", "-inf", "+inf", "LIMIT", "0", "2"),
		cmd("ZRANGEBYSCORE", "z", "-inf", "+inf", "LIMIT", "-1", "5"),
		cmd("ZRANGEBYSCORE", "z", "-inf", "+inf", "LIMIT", "0", "-1"),
		cmd("ZRANGEBYSCORE", "z", "-inf", "+inf", "LIMIT", "99", "2"),
		cmd("ZRANGEBYSCORE", "z", "-inf", "+inf", "WITHSCORES"),
		cmd("ZRANGEBYSCORE", "z", "2", "4", "WITHSCORES", "LIMIT", "1", "10"),
		cmd("ZRANGEBYSCORE", "nokey", "-inf", "+inf"),
		cmd("ZRANGEBYSCORE", "nokey", "abc", "1"),
		cmd("ZRANGEBYSCORE", "z", "abc", "1"),
		cmd("ZRANGEBYSCORE", "z", "1", "abc"),
		cmd("ZRANGEBYSCORE", "z", "(abc", "1"),
		cmd("ZRANGEBYSCORE", "z", "1", "2", "LIMIT", "abc", "1"),
		cmd("ZRANGEBYSCORE", "z", "1", "2", "LIMIT", "1", "abc"),
		cmd("ZRANGEBYSCORE", "z", "1", "2", "LIMIT", "1"),
		cmd("ZRANGEBYSCORE", "z", "1", "2", "BADOPT"),
		cmd("ZREVRANGEBYSCORE", "z", "3", "1"),
		cmd("ZREVRANGEBYSCORE", "z", "3", "(1"),
		cmd("ZREVRANGEBYSCORE", "z", "(3", "1"),
		cmd("ZREVRANGEBYSCORE", "z", "+inf", "-inf", "WITHSCORES"),
		cmd("ZREVRANGEBYSCORE", "z", "+inf", "-inf", "LIMIT", "1", "2"),
		cmd("ZREVRANGEBYSCORE", "z", "1", "3"),
		cmd("ZREVRANGEBYSCORE", "nokey", "+inf", "-inf"),
		// via ZRANGE BYSCORE
		cmd("ZRANGE", "z", "1", "3", "BYSCORE"),
		cmd("ZRANGE", "z", "(1", "(3", "BYSCORE"),
		cmd("ZRANGE", "z", "3", "1", "BYSCORE", "REV"),
		cmd("ZRANGE", "z", "(3", "(1", "BYSCORE", "REV"),
		cmd("ZRANGE", "z", "-inf", "+inf", "BYSCORE", "LIMIT", "1", "2", "WITHSCORES"),
		cmd("ZRANGE", "z", "+inf", "-inf", "BYSCORE", "REV", "LIMIT", "0", "2"),
		cmd("ZRANGE", "z", "-inf", "+inf", "BYSCORE", "REV"),
		cmd("ZRANGE", "z", "abc", "1", "BYSCORE"),
	}},
	{"zset-range-bylex", []step{
		cmd("ZADD", "z", "0", "a", "0", "b", "0", "c", "0", "d", "0", "e"),
		cmd("ZRANGEBYLEX", "z", "-", "+"),
		cmd("ZRANGEBYLEX", "z", "[b", "[d"),
		cmd("ZRANGEBYLEX", "z", "(b", "[d"),
		cmd("ZRANGEBYLEX", "z", "[b", "(d"),
		cmd("ZRANGEBYLEX", "z", "(b", "(d"),
		cmd("ZRANGEBYLEX", "z", "[bb", "+"),
		cmd("ZRANGEBYLEX", "z", "-", "(b"),
		cmd("ZRANGEBYLEX", "z", "[", "+"),
		cmd("ZRANGEBYLEX", "z", "[d", "[b"),
		cmd("ZRANGEBYLEX", "z", "-", "+", "LIMIT", "1", "2"),
		cmd("ZRANGEBYLEX", "z", "-", "+", "LIMIT", "-1", "2"),
		cmd("ZRANGEBYLEX", "z", "-", "+", "LIMIT", "0", "-1"),
		cmd("ZRANGEBYLEX", "nokey", "-", "+"),
		cmd("ZRANGEBYLEX", "z", "a", "b"),
		cmd("ZRANGEBYLEX", "z", "(a", "b"),
		cmd("ZRANGEBYLEX", "z", "[a", "b"),
		cmd("ZRANGEBYLEX", "z", "++", "+"),
		cmd("ZRANGEBYLEX", "z", "--", "+"),
		cmd("ZRANGEBYLEX", "z", "-", "+", "WITHSCORES"),
		cmd("ZRANGEBYLEX", "z", "-", "+", "LIMIT", "abc", "1"),
		cmd("ZLEXCOUNT", "z", "-", "+"),
		cmd("ZLEXCOUNT", "z", "[b", "(e"),
		cmd("ZLEXCOUNT", "z", "[b", "[b"),
		cmd("ZLEXCOUNT", "z", "(b", "(b"),
		cmd("ZLEXCOUNT", "z", "x", "+"),
		cmd("ZLEXCOUNT", "nokey", "-", "+"),
		cmd("ZRANGE", "z", "[b", "[d", "BYLEX"),
		cmd("ZRANGE", "z", "[d", "[b", "BYLEX", "REV"),
		cmd("ZRANGE", "z", "+", "-", "BYLEX", "REV"),
		cmd("ZRANGE", "z", "(e", "(a", "BYLEX", "REV", "LIMIT", "1", "1"),
		cmd("ZRANGE", "z", "0", "-1", "BYLEX"),
		cmd("ZRANGE", "z", "[a", "[c", "BYLEX", "WITHSCORES"),
		cmd("ZREMRANGEBYLEX", "z", "[b", "(d"),
		cmd("ZRANGEBYLEX", "z", "-", "+"),
		cmd("ZREMRANGEBYLEX", "z", "-", "+"),
		cmd("EXISTS", "z"),
		cmd("ZREMRANGEBYLEX", "nokey", "-", "+"),
		cmd("ZREMRANGEBYLEX", "nokey", "bad", "+"),
	}},
	{"zset-rem", []step{
		cmd("ZADD", "z", "1", "a", "2", "b", "3", "c", "4", "d", "5", "e"),
		cmd("ZREM", "z", "b", "no", "d"),
		cmd("ZRANGE", "z", "0", "-1"),
		cmd("ZREM", "nokey", "a"),
		cmd("ZREM", "z"),
		cmd("ZADD", "z2", "1", "a", "2", "b", "3", "c", "4", "d"),
		cmd("ZREMRANGEBYRANK", "z2", "1", "2"),
		cmd("ZRANGE", "z2", "0", "-1", "WITHSCORES"),
		cmd("ZREMRANGEBYRANK", "z2", "-1", "-1"),
		cmd("ZRANGE", "z2", "0", "-1"),
		cmd("ZREMRANGEBYRANK", "z2", "-100", "-1"),
		cmd("EXISTS", "z2"),
		cmd("ZREMRANGEBYRANK", "nokey", "0", "-1"),
		cmd("ZREMRANGEBYRANK", "z3", "abc", "0"),
		cmd("ZADD", "z3", "1", "a"),
		cmd("ZREMRANGEBYRANK", "z3", "5", "10"),
		cmd("ZREMRANGEBYRANK", "z3", "2", "0"),
		cmd("ZADD", "z4", "1", "a", "2", "b", "3", "c", "4", "d", "5", "e"),
		cmd("ZREMRANGEBYSCORE", "z4", "2", "4"),
		cmd("ZRANGE", "z4", "0", "-1"),
		cmd("ZREMRANGEBYSCORE", "z4", "(1", "(5"),
		cmd("EXISTS", "z4"),
		cmd("ZREMRANGEBYSCORE", "nokey", "1", "2"),
		cmd("ZREMRANGEBYSCORE", "nokey", "abc", "2"),
		cmd("ZADD", "z5", "1", "a"),
		cmd("ZREM", "z5", "a"),
		cmd("EXISTS", "z5"),
	}},
	{"zset-count", []step{
		cmd("ZADD", "z", "1", "a", "2", "b", "3", "c", "inf", "pinf", "-inf", "ninf"),
		cmd("ZCARD", "z"),
		cmd("ZCARD", "nokey"),
		cmd("ZCOUNT", "z", "1", "3"),
		cmd("ZCOUNT", "z", "(1", "(3"),
		cmd("ZCOUNT", "z", "-inf", "+inf"),
		cmd("ZCOUNT", "z", "inf", "+inf"),
		cmd("ZCOUNT", "z", "(-inf", "+inf"),
		cmd("ZCOUNT", "z", "5", "1"),
		cmd("ZCOUNT", "nokey", "1", "2"),
		cmd("ZCOUNT", "z", "abc", "2"),
		cmd("ZCOUNT", "z", "1", "abc"),
		cmd("ZCARD", "str-no"),
	}},
	{"zset-pop", []step{
		cmd("ZPOPMIN", "nokey"),
		cmd("ZPOPMAX", "nokey", "2"),
		cmd("ZADD", "z", "1", "a", "2", "b", "3", "c"),
		cmd("ZPOPMIN", "z"),
		cmd("ZPOPMAX", "z"),
		cmd("ZRANGE", "z", "0", "-1"),
		cmd("ZPOPMIN", "z", "5"),
		cmd("EXISTS", "z"),
		cmd("ZADD", "z", "1", "a", "2", "b", "3", "c"),
		cmd("ZPOPMAX", "z", "2"),
		cmd("ZRANGE", "z", "0", "-1", "WITHSCORES"),
		cmd("ZPOPMIN", "z", "0"),
		cmd("ZCARD", "z"),
		cmd("ZPOPMIN", "z", "-1"),
		cmd("ZPOPMIN", "z", "abc"),
		cmd("ZPOPMAX", "z", "-0"),
		cmd("ZADD", "z", "1", "only"),
		cmd("ZPOPMIN", "z", "1"),
		cmd("EXISTS", "z"),
		// equal scores pop in member order
		cmd("ZADD", "ze", "5", "b", "5", "a", "5", "c"),
		cmd("ZPOPMIN", "ze"),
		cmd("ZPOPMAX", "ze"),
	}},
	{"zset-randmember", []step{
		cmd("ZRANDMEMBER", "nokey"),
		cmd("ZRANDMEMBER", "nokey", "3"),
		cmd("ZRANDMEMBER", "nokey", "-3"),
		cmd("ZRANDMEMBER", "nokey", "abc"),
		cmd("ZRANDMEMBER", "nokey", "WITHSCORES"),
		cmd("ZRANDMEMBER", "nokey", "1", "WITHSCORES", "EXTRA"),
		cmd("ZADD", "z", "1", "only"),
		cmd("ZRANDMEMBER", "z"),
		cmd("ZRANDMEMBER", "z", "1"),
		cmd("ZRANDMEMBER", "z", "-3"),
		cmd("ZRANDMEMBER", "z", "-3", "WITHSCORES"),
		cmd("ZRANDMEMBER", "z", "0"),
		cmd("ZADD", "z2", "1", "a", "2", "b", "3", "c"),
		// count >= card: all members (score order here; unordered matcher)
		cmdM(mSetCmp, "ZRANDMEMBER", "z2", "99"),
		cmdM(mPairCmp, "ZRANDMEMBER", "z2", "99", "WITHSCORES"),
	}},
	{"zset-algebra", []step{
		cmd("ZADD", "za", "1", "a", "2", "b", "3", "c"),
		cmd("ZADD", "zb", "2", "b", "4", "c", "5", "d"),
		cmd("ZDIFF", "2", "za", "zb"),
		cmd("ZDIFF", "2", "za", "zb", "WITHSCORES"),
		cmd("ZDIFF", "1", "za", "WITHSCORES"),
		cmd("ZDIFF", "2", "zb", "za"),
		cmd("ZDIFF", "2", "za", "nokey"),
		cmd("ZDIFF", "2", "nokey", "za"),
		cmd("ZINTER", "2", "za", "zb"),
		cmd("ZINTER", "2", "za", "zb", "WITHSCORES"),
		cmd("ZUNION", "2", "za", "zb", "WITHSCORES"),
		cmd("ZUNION", "2", "za", "zb"),
		cmd("ZINTER", "2", "za", "nokey"),
		cmd("ZINTER", "1", "za", "WITHSCORES"),
		cmd("ZUNION", "1", "za"),
		// sets participate with score 1
		cmd("SADD", "s", "a", "b", "x"),
		cmd("ZUNION", "2", "za", "s", "WITHSCORES"),
		cmd("ZINTER", "2", "za", "s", "WITHSCORES"),
		cmd("ZDIFF", "2", "za", "s", "WITHSCORES"),
		cmd("ZUNION", "2", "s", "s", "WITHSCORES"),
		// errors
		cmd("ZDIFF", "abc", "za"),
		cmd("ZDIFF", "0"),
		cmd("ZDIFF", "5", "za", "zb"),
		cmd("ZDIFF", "1", "za", "BADOPT"),
		cmd("ZDIFF", "1", "za", "WITHSCORES", "EXTRA"),
		cmd("ZINTER", "1", "za", "za", "WITHSCORES"),
		cmd("ZUNION", "0"),
		cmd("SET", "str", "v"),
		cmd("ZUNION", "1", "str"),
		cmd("ZDIFF", "1", "str"),
	}},
	{"zset-stores", []step{
		cmd("ZADD", "za", "1", "a", "2", "b", "3", "c"),
		cmd("ZADD", "zb", "2", "b", "4", "c", "5", "d"),
		cmd("ZUNIONSTORE", "d", "2", "za", "zb"),
		cmd("ZRANGE", "d", "0", "-1", "WITHSCORES"),
		cmd("TYPE", "d"),
		cmd("ZINTERSTORE", "d", "2", "za", "zb"),
		cmd("ZRANGE", "d", "0", "-1", "WITHSCORES"),
		cmd("ZUNIONSTORE", "d", "2", "za", "zb", "WEIGHTS", "2", "3"),
		cmd("ZRANGE", "d", "0", "-1", "WITHSCORES"),
		cmd("ZUNIONSTORE", "d", "2", "za", "zb", "WEIGHTS", "0.5", "-1"),
		cmd("ZRANGE", "d", "0", "-1", "WITHSCORES"),
		cmd("ZUNIONSTORE", "d", "2", "za", "zb", "AGGREGATE", "MIN"),
		cmd("ZRANGE", "d", "0", "-1", "WITHSCORES"),
		cmd("ZUNIONSTORE", "d", "2", "za", "zb", "AGGREGATE", "MAX"),
		cmd("ZRANGE", "d", "0", "-1", "WITHSCORES"),
		cmd("ZINTERSTORE", "d", "2", "za", "zb", "WEIGHTS", "2", "2", "AGGREGATE", "MIN"),
		cmd("ZRANGE", "d", "0", "-1", "WITHSCORES"),
		cmd("ZUNIONSTORE", "d", "2", "za", "zb", "AGGREGATE", "MIN", "WEIGHTS", "2", "2"),
		cmd("ZRANGE", "d", "0", "-1", "WITHSCORES"),
		// empty result deletes dest
		cmd("ZINTERSTORE", "d", "2", "za", "nokey"),
		cmd("EXISTS", "d"),
		cmd("ZUNIONSTORE", "d", "2", "nokey", "nokey2"),
		cmd("EXISTS", "d"),
		// store over a string
		cmd("SET", "d", "str"),
		cmd("ZUNIONSTORE", "d", "1", "za"),
		cmd("TYPE", "d"),
		// set inputs score 1
		cmd("SADD", "s", "a", "x"),
		cmd("ZUNIONSTORE", "d", "2", "za", "s"),
		cmd("ZRANGE", "d", "0", "-1", "WITHSCORES"),
		cmd("ZINTERSTORE", "d", "2", "za", "s"),
		cmd("ZRANGE", "d", "0", "-1", "WITHSCORES"),
		// inf + -inf folds NaN to 0
		cmd("ZADD", "zi", "inf", "a"),
		cmd("ZADD", "zj", "-inf", "a", "2", "b"),
		cmd("ZUNIONSTORE", "d", "2", "zi", "zj"),
		cmd("ZRANGE", "d", "0", "-1", "WITHSCORES"),
		// errors
		cmd("ZUNIONSTORE", "d", "abc", "za"),
		cmd("ZUNIONSTORE", "d", "0"),
		cmd("ZUNIONSTORE", "d", "5", "za", "zb"),
		cmd("ZUNIONSTORE", "d", "2", "za", "zb", "WEIGHTS", "1"),
		cmd("ZUNIONSTORE", "d", "2", "za", "zb", "WEIGHTS", "1", "2", "3"),
		cmd("ZUNIONSTORE", "d", "2", "za", "zb", "WEIGHTS", "1", "abc"),
		cmd("ZUNIONSTORE", "d", "2", "za", "zb", "WEIGHTS", "1", "nan"),
		cmd("ZUNIONSTORE", "d", "2", "za", "zb", "AGGREGATE", "BAD"),
		cmd("ZUNIONSTORE", "d", "2", "za", "zb", "BADOPT"),
		cmd("ZUNIONSTORE", "d", "1", "str"),
		cmd("ZUNIONSTORE"),
	}},
	{"zset-scan", []step{
		cmd("ZADD", "z", "1", "a", "2", "b", "3", "c", "4", "d"),
		cmdM(mScanAllPairs, "ZSCAN", "z", "0", "COUNT", "1000"),
		cmdM(mScanAllPairs, "ZSCAN", "z", "0", "MATCH", "[ab]", "COUNT", "1000"),
		cmdM(mScanAllPairs, "ZSCAN", "z", "0", "MATCH", "nada*"),
		cmdM(mScanAllPairs, "ZSCAN", "nokey", "0"),
		{args: []string{"ZSCANLOOP", "z"}, m: mEq},
		cmd("ZSCAN", "z", "abc"),
		cmd("ZSCAN", "z", "0", "COUNT", "0"),
		cmd("SET", "str", "v"),
		cmd("ZSCAN", "str", "0"),
	}},
	{"zset-wrongtype", []step{
		cmd("SET", "str", "v"),
		cmd("ZSCORE", "str", "m"),
		cmd("ZMSCORE", "str", "m"),
		cmd("ZINCRBY", "str", "1", "m"),
		cmd("ZRANK", "str", "m"),
		cmd("ZREVRANK", "str", "m", "WITHSCORE"),
		cmd("ZRANGE", "str", "0", "-1"),
		cmd("ZRANGEBYSCORE", "str", "0", "1"),
		cmd("ZRANGEBYLEX", "str", "-", "+"),
		cmd("ZREVRANGE", "str", "0", "-1"),
		cmd("ZREVRANGEBYSCORE", "str", "1", "0"),
		cmd("ZREMRANGEBYRANK", "str", "0", "-1"),
		cmd("ZREMRANGEBYSCORE", "str", "0", "1"),
		cmd("ZREMRANGEBYLEX", "str", "-", "+"),
		cmd("ZCARD", "str"),
		cmd("ZCOUNT", "str", "0", "1"),
		cmd("ZLEXCOUNT", "str", "-", "+"),
		cmd("ZREM", "str", "m"),
		cmd("ZPOPMIN", "str"),
		cmd("ZPOPMAX", "str", "1"),
		cmd("ZRANDMEMBER", "str"),
		cmd("ZRANDMEMBER", "str", "1"),
		cmd("ZADD", "z", "1", "a"),
		cmd("ZINTERSTORE", "d", "1", "str"),
		cmd("HSET", "h", "f", "v"),
		cmd("ZUNIONSTORE", "d", "1", "h"),
		cmd("LPUSH", "l", "x"),
		cmd("ZUNIONSTORE", "d", "1", "l"),
	}},
	{"zset-expiry", []step{
		cmd("ZADD", "zx", "1", "a"),
		cmd("PEXPIRE", "zx", "150"),
		cmd("ZSCORE", "zx", "a"),
		cmd("SLEEP", "250"),
		cmd("ZSCORE", "zx", "a"),
		cmd("EXISTS", "zx"),
	}},
	{"zset-large", func() []step {
		pairs := []string{}
		for i := 0; i < 300; i++ {
			pairs = append(pairs, strconv.Itoa(i*7%997), "m"+itoa(i))
		}
		steps := []step{cmd(append([]string{"ZADD", "big"}, pairs...)...)}
		steps = append(steps,
			cmd("ZCARD", "big"),
			cmd("ZRANGE", "big", "0", "4", "WITHSCORES"),
			cmd("ZRANGE", "big", "-3", "-1", "WITHSCORES"),
			cmd("ZRANK", "big", "m150"),
			cmd("ZCOUNT", "big", "100", "200"),
			cmd("ZRANGEBYSCORE", "big", "100", "105", "WITHSCORES"),
			cmd("ZREMRANGEBYSCORE", "big", "0", "50"),
			cmd("ZCARD", "big"),
			step{args: []string{"ZSCANLOOP", "big"}, m: mEq},
		)
		return steps
	}()},
}

// resp3Scripts run through HELLO 3: RESP3-specific reply shapes (maps,
// sets, doubles, nested score pairs).
var p1Resp3Scripts = []script{
	{"resp3-collections", []step{
		cmdM(mHello, "HELLO", "3"),
		cmd("HSET", "h", "a", "1", "b", "2"),
		cmd("HGETALL", "h"),                       // map
		cmd("HGETALL", "nokey"),                   // empty map
		cmd("HSCAN", "h", "0"),                    // flat pair array even in RESP3
		cmd("HRANDFIELD", "h", "5", "WITHVALUES"), // all fields, nested pairs
		cmd("HRANDFIELD", "nokey", "2"),
		cmd("SADD", "s", "1", "2", "3"),
		cmd("SMEMBERS", "s"),     // set type, intset order
		cmd("SMEMBERS", "nokey"), // empty set type
		cmd("SPOP", "s", "99"),   // set type, all
		cmd("SADD", "s", "1", "2", "3"),
		cmd("SINTER", "s", "s"), // set type
		cmd("SUNION", "s", "nokey"),
		cmd("SDIFF", "s", "s"),
		cmd("SRANDMEMBER", "s", "99"), // array (not set), all
		cmd("ZADD", "z", "1", "a", "0.1", "b", "inf", "c"),
		cmd("ZSCORE", "z", "a"), // double
		cmd("ZSCORE", "z", "b"),
		cmd("ZSCORE", "z", "c"),
		cmd("ZSCORE", "z", "no"),
		cmd("ZMSCORE", "z", "a", "no", "b"),
		cmd("ZINCRBY", "z", "0.5", "a"),
		cmd("ZADD", "z", "INCR", "0.25", "a"),
		cmd("ZRANGE", "z", "0", "-1", "WITHSCORES"), // nested pairs w/ doubles
		cmd("ZRANK", "z", "b", "WITHSCORE"),
		cmd("ZREVRANK", "z", "no", "WITHSCORE"),
		cmd("ZPOPMIN", "z"),      // flat [member, double]
		cmd("ZPOPMAX", "z", "5"), // nested pairs
		cmd("ZRANDMEMBER", "nokey", "2"),
		cmd("LPUSH", "l", "x"),
		cmd("LPOP", "l"),
		cmd("LPOP", "nokey", "2"),
	}},
}

var p1Scripts = func() []script {
	var out []script
	out = append(out, p1HashScripts...)
	out = append(out, p1ListScripts...)
	out = append(out, p1SetScripts...)
	out = append(out, p1ZSetScripts...)
	out = append(out, p1Resp3Scripts...)
	return out
}()
