package differential

// P0 coverage scripts (§7). Each script starts from an empty keyspace
// (the runner FLUSHALLs first). SLEEP is a harness pseudo-command.

import "strconv"

var p0Scripts = []script{
	{"ping-echo-quit", []step{
		cmd("PING"),
		cmd("PING", "hello world"),
		cmd("PING", "a", "b"),
		cmd("ECHO", "xyzzy"),
		cmd("ECHO"),
	}},
	{"set-options", []step{
		cmd("SET", "k", "v"),
		cmd("GET", "k"),
		cmd("SET", "k", "v2", "NX"),
		cmd("GET", "k"),
		cmd("SET", "k", "v2", "XX"),
		cmd("GET", "k"),
		cmd("SET", "nokey", "v", "XX"),
		cmd("SET", "k", "v3", "GET"),
		cmd("SET", "k", "v4", "GET", "NX"),
		cmd("SET", "gone", "v", "GET", "XX"),
		cmd("SET", "k", "v5", "GET", "EX", "100"),
		cmdM(mTTL, "TTL", "k"),
		// error matrix
		cmd("SET", "k", "v", "NX", "XX"),
		cmd("SET", "k", "v", "XX", "NX"),
		cmd("SET", "k", "v", "KEEPTTL", "EX", "10"),
		cmd("SET", "k", "v", "EX", "10", "KEEPTTL"),
		cmd("SET", "k", "v", "EX", "0"),
		cmd("SET", "k", "v", "PX", "-5"),
		cmd("SET", "k", "v", "EX", "abc"),
		cmd("SET", "k", "v", "PXAT", "abc"),
		cmd("SET", "k", "v", "BADOPT"),
		cmd("SET", "k", "v", "EX"),
		cmd("SET", "k", "v", "EX", "10", "EX", "20"),
		cmdM(mTTL, "TTL", "k"),
		cmd("SET", "k", "v", "EX", "10", "PX", "10000"),
		cmd("SET", "k", "v", "NX", "NX", "NX"),
		cmd("SET", "k", "v", "KEEPTTL", "KEEPTTL"),
		// past absolute expiry deletes
		cmd("SET", "ph", "v", "EXAT", "1"),
		cmd("EXISTS", "ph"),
		cmd("SET", "ph", "v", "PXAT", "1"),
		cmd("EXISTS", "ph"),
	}},
	{"get-family", []step{
		cmd("GET", "missing"),
		cmd("SET", "g", "old"),
		cmd("GETSET", "g", "new"),
		cmd("GET", "g"),
		cmd("GETSET", "absent", "x"),
		cmd("GET", "absent"),
		cmd("GETDEL", "g"),
		cmd("GET", "g"),
		cmd("GETDEL", "g"),
		cmd("GETSET", "g"), // arity
		cmd("GETEX", "nokey", "BADOPT"),
		cmd("GETEX", "nokey", "EX", "0"),
		cmd("GETEX", "nokey", "EX", "abc"),
		cmd("SET", "gx", "v"),
		cmd("GETEX", "gx"),
		cmd("GETEX", "gx", "EX", "200"),
		cmdM(mTTL, "TTL", "gx"),
		cmd("GETEX", "gx", "PERSIST"),
		cmd("TTL", "gx"),
		cmd("GETEX", "gx", "PERSIST"),
		cmd("GETEX", "gx", "EX", "0"),
		cmd("GETEX", "gx", "PERSIST", "EX", "10"),
		cmd("GETEX", "gx", "EX", "10", "PERSIST"),
		cmd("GETEX", "gx", "EXAT", "abc"),
		cmd("GETEX", "gx", "PXAT", "1"), // returns value, deletes key
		cmd("EXISTS", "gx"),
	}},
	{"counters", []step{
		cmd("INCR", "n"),
		cmd("INCRBY", "n", "9"),
		cmd("DECR", "n"),
		cmd("DECRBY", "n", "4"),
		cmd("GET", "n"),
		cmd("SET", "bad", "abc"),
		cmd("INCR", "bad"),
		cmd("INCRBY", "bad", "5"),
		cmd("DECRBY", "bad", "1"),
		cmd("INCRBY", "n", "abc"),
		cmd("INCRBY", "n", "1.5"),
		cmd("SET", "max", "9223372036854775807"),
		cmd("INCR", "max"),
		cmd("INCRBY", "max", "10"),
		cmd("SET", "min", "-9223372036854775808"),
		cmd("DECR", "min"),
		cmd("DECRBY", "min", "1"),
		cmd("DECRBY", "other", "-9223372036854775808"),
		cmd("GET", "other"),
		cmd("INCR", "n", "extra"),
	}},
	{"incrbyfloat", []step{
		cmd("INCRBYFLOAT", "f", "1.1"),
		cmd("INCRBYFLOAT", "f", "1.1"),
		cmd("GET", "f"),
		cmd("INCRBYFLOAT", "g", "0.3"),
		cmd("INCRBYFLOAT", "g", "0.3"),
		cmd("GET", "g"),
		cmd("INCRBYFLOAT", "i", "5"),
		cmd("INCRBYFLOAT", "i", "3e3"),
		cmd("INCRBYFLOAT", "i", ".5"),
		cmd("INCRBYFLOAT", "i", "0x10"),
		cmd("SET", "fstr", "abc"),
		cmd("INCRBYFLOAT", "fstr", "1"),
		cmd("INCRBYFLOAT", "f", "nan"),
		cmd("INCRBYFLOAT", "f", "inf"),
		cmd("INCRBYFLOAT", "f", "-inf"),
		cmd("INCRBYFLOAT", "f", "1e9999"),
		cmd("INCRBYFLOAT", "f", "1e-9999"),
		cmd("INCRBYFLOAT", "big", "1.7976931348623157e308"),
		cmd("INCRBYFLOAT", "big", "1e308"),
		cmd("INCRBYFLOAT", "tiny", "1e-20"), // rounds to "0" at 17 digits
		cmd("INCRBYFLOAT", "e", "1e300"),
		cmd("RPUSH", "fl", "x"),
		cmd("INCRBYFLOAT", "fl", "1"),
	}},
	{"append-strlen", []step{
		cmd("APPEND", "a", "hello"),
		cmd("APPEND", "a", " "),
		cmd("APPEND", "a", "world"),
		cmd("GET", "a"),
		cmd("STRLEN", "a"),
		cmd("STRLEN", "missing"),
		cmd("TYPE", "a"),
		cmd("TYPE", "missing"),
		cmd("APPEND", "a"), // arity
	}},
	{"multi-key", []step{
		cmd("MSET", "m1", "v1", "m2", "v2", "m3", "v3"),
		cmd("MGET", "m1", "m2", "m3", "missing"),
		cmd("MSET", "odd", "v", "unbalanced"),
		cmd("MGET"),
		cmd("MSETNX", "n1", "1", "n2", "2"),
		cmd("MSETNX", "n1", "9", "n3", "3"),
		cmd("GET", "n3"),
		cmd("EXISTS", "n1", "n2", "missing", "n1"), // duplicate counts
		cmd("DEL", "n1", "n2", "missing"),
		cmd("EXISTS", "n1", "n2"),
		cmd("DEL"),
	}},
	{"expire-family", []step{
		cmd("SET", "e", "v"),
		cmd("EXPIRE", "e", "100"),
		cmdM(mTTL, "TTL", "e"),
		cmd("EXPIRE", "e", "200", "NX"), // has TTL: fails
		cmd("EXPIRE", "e", "50", "GT"),  // 50 < 100: fails
		cmd("EXPIRE", "e", "300", "GT"), // succeeds
		cmdM(mTTL, "TTL", "e"),
		cmd("EXPIRE", "e", "300", "LT"), // not less: fails
		cmd("EXPIRE", "e", "100", "LT"), // succeeds
		cmd("EXPIRE", "e", "10", "XX"),  // has TTL: succeeds
		cmd("PERSIST", "e"),
		cmd("TTL", "e"),
		cmd("PERSIST", "e"),
		cmd("EXPIRE", "e", "100", "XX"), // no TTL: fails
		cmd("PEXPIRE", "e", "100000"),
		cmdM(mTTL, "PTTL", "e"),
		cmd("TTL", "missing"),
		cmd("PTTL", "missing"),
		cmd("PERSIST", "missing"),
		cmd("EXPIRE", "missing", "10"),
		cmd("EXPIRE", "missing", "10", "XX"),
		cmd("EXPIRE", "missing", "abc"),
		cmd("EXPIRE", "e", "abc"),
		cmd("EXPIRE", "e", "10", "NX", "XX"),
		cmd("EXPIRE", "e", "10", "NX", "GT"),
		cmd("EXPIRE", "e", "10", "GT", "LT"),
		cmd("EXPIRE", "e", "10", "BADOPT"),
		// zero/negative expire deletes the key
		cmd("EXPIRE", "e", "0"),
		cmd("EXISTS", "e"),
		cmd("SET", "e", "v"),
		cmd("PEXPIRE", "e", "-1"),
		cmd("EXISTS", "e"),
	}},
	{"expiry-sleep", []step{
		cmd("SET", "s", "v", "PX", "120"),
		cmd("SLEEP", "220"),
		cmd("GET", "s"),
		cmd("EXISTS", "s"),
		cmd("TTL", "s"),
		cmd("SET", "s2", "v"),
		cmd("PEXPIRE", "s2", "100"),
		cmd("SLEEP", "200"),
		cmd("GET", "s2"),
	}},
	{"scan", []step{
		cmd("MSET", "user:1", "a", "user:2", "b", "user:3", "c", "other:1", "d", "zz", "e"),
		cmdM(mScanAll, "SCAN", "0", "COUNT", "1000"),
		cmdM(mScanAll, "SCAN", "0", "MATCH", "user:*", "COUNT", "1000"),
		cmdM(mScanAll, "SCAN", "0", "MATCH", "other:?"),
		cmdM(mScanAll, "SCAN", "0", "MATCH", "no-match-*"),
		// incremental iteration terminates
		cmd("SCAN", "abc"),
		cmd("SCAN", "0", "COUNT", "-5"),
		cmd("SCAN", "0", "COUNT", "abc"),
		cmd("SCAN", "0", "MATCH"),
		cmd("SCAN", "0", "BADARG", "x"),
		cmd("SCAN"),
	}},
	{"scan-incremental", func() []step {
		// enough keys that COUNT 10 needs multiple rounds on both servers
		steps := []step{}
		pairs := []string{}
		for i := 0; i < 60; i++ {
			pairs = append(pairs, "sk"+itoa(i), "v")
		}
		steps = append(steps, cmd(append([]string{"MSET"}, pairs...)...))
		// walk cursors in lockstep as far as they agree; both must finish
		steps = append(steps, step{args: []string{"SCANLOOP"}, m: mEq})
		return steps
	}()},
	{"select-dbs", []step{
		cmd("SELECT", "3"),
		cmd("SET", "dk", "in-db3"),
		cmd("SELECT", "0"),
		cmd("GET", "dk"),
		cmd("SELECT", "3"),
		cmd("GET", "dk"),
		cmd("DBSIZE"),
		cmd("FLUSHDB"),
		cmd("DBSIZE"),
		cmd("SELECT", "0"),
		cmd("SET", "dk", "in-db0"),
		cmd("DBSIZE"),
		cmd("FLUSHALL"),
		cmd("SELECT", "3"),
		cmd("DBSIZE"),
		cmd("SELECT", "16"),
		cmd("SELECT", "-1"),
		cmd("SELECT", "abc"),
		cmd("SELECT", "0"),
		cmd("FLUSHDB", "ASYNC"),
		cmd("FLUSHDB", "SYNC"),
		cmd("FLUSHDB", "BADOPT"),
		cmd("FLUSHDB", "SYNC", "EXTRA"),
		cmd("FLUSHALL", "ASYNC"),
	}},
	{"info-dbsize-flush", []step{
		cmd("DBSIZE"),
		cmd("MSET", "i1", "a", "i2", "b", "i3", "c"),
		cmd("DBSIZE"),
		cmdM(mInfo, "INFO"),
		cmdM(mInfo, "INFO", "server"),
		cmdM(mInfo, "INFO", "keyspace"),
		cmd("INFO", "nosuchsection"),
		cmd("FLUSHDB"),
		cmd("DBSIZE"),
	}},
	{"config", []step{
		cmdM(mConfigPairs, "CONFIG", "GET", "maxmemory"),
		cmdM(mConfigPairs, "CONFIG", "GET", "requirepass"),
		cmdM(mConfigPairs, "CONFIG", "GET", "appendonly"),
		cmdM(mConfigPairs, "CONFIG", "GET", "databases"),
		cmdM(mConfigPairs, "CONFIG", "GET", "nosuchparam"),
		cmd("CONFIG", "GET"),
		cmd("CONFIG", "SET", "maxmemory", "100mb"),
		cmdM(mConfigPairs, "CONFIG", "GET", "maxmemory"),
		cmd("CONFIG", "SET", "maxmemory", "0"),
		cmd("CONFIG", "SET", "maxmemory", "abc"),
		cmd("CONFIG", "SET", "maxmemory", "-5"),
		cmd("CONFIG", "SET", "nosuchparam", "1"),
		cmd("CONFIG", "SET", "databases", "32"),
		cmd("CONFIG", "SET", "save", ""),
		cmdM(mConfigPairs, "CONFIG", "GET", "save"),
		cmd("CONFIG", "SET", "save", "bad params here"),
		cmd("CONFIG", "SET", "appendonly", "maybe"),
		cmd("CONFIG", "NOSUB"),
		cmd("CONFIG"),
	}},
	{"client-cmd", []step{
		cmd("CLIENT", "SETNAME", "diff-conn"),
		cmd("CLIENT", "GETNAME"),
		cmd("CLIENT", "SETNAME", ""),
		cmd("CLIENT", "GETNAME"),
		cmd("CLIENT", "SETNAME", "bad name"),
		cmdM(mAnyInt, "CLIENT", "ID"),
		cmd("CLIENT", "SETINFO", "lib-name", "diff-harness"),
		cmd("CLIENT", "NOSUB"),
		cmd("CLIENT"),
		cmd("CLIENT", "SETNAME"),
	}},
	{"command-meta", []step{
		cmdM(mCount, "COMMAND", "COUNT"),
		cmdM(mCommandInfo, "COMMAND", "INFO", "get", "set", "mget"),
		cmdM(mCommandInfo, "COMMAND", "INFO", "nosuchcmd"),
		cmd("COMMAND", "NOSUB"),
		cmdM(mAnyArr, "COMMAND"),
	}},
	{"unknown-and-arity", []step{
		cmd("FOOCMD", "a", "b"),
		cmd("FOOCMD"),
		cmd("GET"),
		cmd("GET", "a", "b"),
		cmd("MGET"),
		cmd("SET", "onlykey"),
		cmd("TTL"),
		cmd("PING", "a", "b"),
	}},
	{"hello", []step{
		cmdM(mHello, "HELLO"),
		cmd("HELLO", "4"),
		cmd("HELLO", "0"),
		cmd("HELLO", "x"),
		cmd("HELLO", "3", "FOO"),
		cmd("HELLO", "3", "AUTH", "default"),
		cmd("HELLO", "3", "SETNAME"),
		cmdM(mHello, "HELLO", "2"),
		cmdM(mHello, "HELLO", "2", "SETNAME", "hi"),
		cmd("CLIENT", "GETNAME"),
	}},
	{"binary-safe", []step{
		cmd("SET", "bin", "a\x00b\xffc"),
		cmd("GET", "bin"),
		cmd("APPEND", "bin", "\x00"),
		cmd("STRLEN", "bin"),
		cmd("SET", "empty", ""),
		cmd("GET", "empty"),
		cmd("STRLEN", "empty"),
		cmd("EXISTS", "empty"),
	}},
	{"resp3", []step{ // run through HELLO 3 first, same compare rules
		cmdM(mHello, "HELLO", "3"),
		cmd("SET", "r3", "v"),
		cmd("GET", "r3"),
		cmd("GET", "missing"), // RESP3 null on both
		cmd("MGET", "r3", "missing"),
		cmd("TYPE", "r3"),
		cmd("CONFIG", "GET", "maxmemory"),
		cmd("SCAN", "0"),
	}},
}

func itoa(i int) string {
	return strconv.Itoa(i)
}
